name: Meson

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install requirements
        run: |
          sudo apt-get install -y libjson-c-dev python3-pyudev python3-systemd python3-gi meson
          python -m pip install --upgrade pip dasbus pylint pyflakes

      - uses: BSFishy/meson-build@v1.0.3
        with:
          setup-options: --werror
          options: --verbose
          action: test

      - name: Upload logs
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: meson-logs
          path: |
            ${{ github.workspace }}/.build/meson-logs/*.txt

