name: Meson

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install requirements
        run: |
          sudo apt-get install -y python3-pyudev python3-systemd python3-gi meson
          python -m pip install --upgrade pip dasbus pylint pyflakes

      - name: Checkout private libnvme-tp8010
        uses: actions/checkout@v2
        with:
          repository: martin-belanger/libnvme-tp8010
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: libnvme-tp8010
          ref: kernel-dim

      - name: Build and install libnvme-tp8010
        run: |
          cd libnvme-tp8010
          meson .build
          cd .build
          ninja
          sudo meson install

      - name: Configure nvme-stas
        run: PYTHONPATH=libnvme-tp8010/.build meson .build

      - name: Test
        run: |
          cd .build
          PYTHONPATH=../libnvme-tp8010/.build meson test -v

      - name: Upload logs
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: meson-logs
          path: |
            ${{ github.workspace }}/.build/meson-logs/*.txt

