name: Meson

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install requirements
        run: |
          sudo apt-get install -y python3-pyudev python3-systemd python3-gi python3-netifaces meson
          python -m pip install --upgrade pip dasbus pylint pyflakes

      - name: Checkout libnvme
        uses: actions/checkout@v2
        with:
          repository: linux-nvme/libnvme
          path: libnvme

      - name: Build and install libnvme
        run: |
          cd libnvme
          meson .build
          cd .build
          ninja
          sudo meson install

      - name: Configure nvme-stas
        run: PYTHONPATH=libnvme/.build meson .build

      - name: Test
        run: |
          cd .build
          PYTHONPATH=../libnvme/.build meson test -v

      - name: Upload logs
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: meson-logs
          path: |
            ${{ github.workspace }}/.build/meson-logs/*.txt

